Achieve all DTO-OTD tests for entities
maxdlr/bde-platform pull request #18
Opened 2024-02-20 18:07 UTC by Louis-Cauvet

2024-02-20 18:25 UTC, mmoyaerts approved these changes

2024-02-21 06:43 UTC, maxdlr requested changes

2024-02-21 06:43 UTC, maxdlr commented on sql-dumps/createdb.sql
> +    signedUpDate dateTime     not null,
Je comprends mais la variable à garder dans cette erreur que tu essayes de fix est signedUpOn.

J'ai eu le même problème dans l'autre sens. 

Mais depuis le début cette variable est signedUpOn sur figma.

2024-02-21 06:43 UTC, maxdlr commented on tests/InterestedDTOAndOTDTest.php
> +<?php
Du coup tu peux renommer.
Ce n'est plus le dto précisément qu'on test.
C'est l'entity interested en général.

InterestedTest.php

testUserCanAddEventToInterested()

testUserCanRemoveEventFromInterested()

.... Etc

2024-02-21 06:43 UTC, maxdlr commented on tests/ParticipantDTOAndOTDTest.php
> +<?php
Idem

2024-02-21 06:43 UTC, maxdlr commented on tests/UserDTOAndOTDTest.php
> +<?php
Idem

2024-02-21 06:43 UTC, maxdlr commented on tests/UserTest.php
> -    {
Fichier a supprimer.

Ce qu'il y a dedans pourras aller dans 

UserTest.php (anciennement UserDtoAndOtdTest.php)

2024-02-21 17:35 UTC, merged