Integrate system for redirect when url is in 'events/{id}' format
maxdlr/bde-platform pull request #19
Opened 2024-02-20 21:24 UTC by Louis-Cauvet

2024-02-20 21:45 UTC, mmoyaerts approved these changes

2024-02-21 00:35 UTC, maxdlr requested changes
C'est cool mais il faut trouver un moyen de rendre ça abstrait.

2024-02-21 00:35 UTC, maxdlr commented on src/Routing/Router.php
> +        $regExpr2 = "#/events/(\d+)#";
Trop specific aux events

2024-02-21 00:35 UTC, maxdlr commented on src/Routing/Router.php
> +            if($method === "App\Controller\EventController::detail" && $paramTypeFQCN === "int") {
Pareil

2024-02-21 00:35 UTC, maxdlr commented on src/Routing/Router.php
> +        if($method == "detail") {
Trop specific

2024-02-21 12:00 UTC, maxdlr approved these changes

2024-02-21 13:19 UTC, merged