Create entity user + first tests
maxdlr/bde-platform pull request #6
Opened 2024-02-19 22:05 UTC by Louis-Cauvet

2024-02-19 22:51 UTC, maxdlr commented on src/Entity/User.php
> +    private string $mailAdress;
nom de variable: $email

2024-02-19 22:56 UTC, maxdlr requested changes

2024-02-19 22:56 UTC, maxdlr commented on src/Entity/User.php
> +    private string $mailAdress;
nom de variable: $email

2024-02-19 22:56 UTC, maxdlr commented on src/Entity/User.php
> +    public function setMailAdress(string $mailAdress): void
pareil

2024-02-19 22:56 UTC, maxdlr commented on src/Entity/User.php
> +        $this->mailAdress = $mailAdress;
pareil

2024-02-19 22:56 UTC, maxdlr commented on src/Entity/User.php
> +    public function setFirstname(string $firstname): void
Fait des fonction chainées pour les setters.
Ca deviendra donc: 

```php
public function set***(): static
{
      $this->firstname = $firstname;
      return $this;
}
```

2024-02-19 22:56 UTC, maxdlr commented on tests/UserTest.php
> +    public function testValidityMailAdressFormat()
Change pour un nom plus logique:
```php
testEmailFormat()
```
On se doute bien que cest la validité du format que tu test.

2024-02-19 23:58 UTC, Louis-Cauvet reviewed
@maxdlr J'ai revu ce que tu m'a remonté, merci pour les indications

2024-02-20 08:53 UTC, mmoyaerts approved these changes

2024-02-20 08:54 UTC, merged